

spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:refilldb
    username : sa
    initialization-mode: always
  jackson:
    default-property-inclusion: non-null


logging:
  level:
    org:
      springframework: info




server:
  servlet:
    context-path: /refillapp
  port: 8454
  
Exception:
  message: Invalid Token